### ISSUE TITLE
Add to Node package repository

### ISSUE THREAD

**Issue by stu-greenshoots** [opendialogai/vue-beautiful-chat#14]
View the instructions here:
https://docs.npmjs.com/packages-and-modules/contributing-packages-to-the-registry

Add vue-beautiful-chat to the registry, update docs for installation, and update webcaht to use the registry rather than github directly

**Comment by elliotmassen** [comment]
This package is now published to NPM: https://www.npmjs.com/package/@opendialogai/vue-beautiful-chat

**Comment by elliotmassen** [comment]
As discussed with @stu-greenshoots, we aren't currently able to have `opendialogai/webchat` depend on the NPM registry source of this project just yet as NPM doesn't allow for us to depend on a specific branch (as Composer does). For now the dependency will be directly on the GitHub repository.

**Comment by stu-greenshoots** [comment]
But we will use the NPM registry directly when using tagged releases
